package com.example.pulse.event;

/**
 * The kind of system an event came from.
 * <p>
 * An enum rather than a free-form string: adding a source always requires a new adapter anyway,
 * so the set of sources is known at compile time and typos are impossible.
 */
public enum Source {

	RSS,
	HACKER_NEWS,
	GITHUB,
	REDDIT,
	WIKIPEDIA,

	/** Generated by the load-test event generator; never mixed up with real traffic. */
	SYNTHETIC

}
